---
title: "Bias Variance Tradeoff"
output: html_document
---

## Simulation Study with polyester

Load libraries and helper functions

```{r}
paper_path <- "/net/irizarryfs01/srv/export/irizarryfs01_backed_up/share_root/shicks/papers/qsmooth/"

library(polyester)
library(edgeR)
library(Biostrings)
library(preprocessCore)
library(quantro)
library(qsmooth)
library(genefilter)
library(limma)
library(abind)
library(doParallel)
library(ggplot2)
library(dplyr)
library(tidyr)
library(cowplot)

nCores <- 1
registerDoParallel(cores = nCores)
workers <- getDoParWorkers()
backend <- getDoParName()
version <- getDoParVersion()

acomb <- function(...) abind(..., along=3)
comb <- function(x, a) {
    lapply(seq_along(a), function(ii){
        abind::abind(x[[ii]], a[[ii]], along = 2) })
}

# load gene-level read counts (3 control, 3 treated zebrafish)
library(zebrafishRNASeq)
data(zfGenes)
filter <- apply(zfGenes, 1, function(x) length(x[x>5])>=2)
counts <- zfGenes[filter,]

# modify polyester::get_params to change to log2 transformation
get_params <- function (counts, threshold = NULL) 
{
    if (!is.null(threshold)) {
        rowm = rowMeans(counts)
        index1 = which(rowm > threshold)
        counts = counts[index1, ]
    }
    nsamples = dim(counts)[2]
    counts0 = counts == 0
    nn0 = rowSums(!counts0)
    if (any(nn0 == 1)) {
        counts = counts[nn0 > 1, ]
        nn0 = nn0[nn0 > 1]
        counts0 = counts == 0
    }
    mu = rowSums((!counts0) * counts)/nn0
    s2 = rowSums((!counts0) * (counts - mu)^2)/(nn0 - 1)
    size = mu^2/(s2 - mu + 1e-04)
    size = ifelse(size > 0, size, min(size[size > 0]))
    p0 = (nsamples - nn0)/nsamples
    lsize = log2(size)
    lmu = log2(mu + 1e-04)
    fit = smooth.spline(lsize ~ lmu)
    return(list(p0 = p0, mu = mu, size = size, fit = fit))
}

params = get_params(counts)

# modify polyester::create_read_numbers to include sample-level scaling factor (scaleFac)
create_read_numbers <- function(mu, fit, p0, m = NULL, n = NULL, 
                                mod = NULL, beta = NULL, seed = NULL, 
                                scaleFac = NULL) 
{
    m = dim(beta)[1]
    n = dim(mod)[1]
    index = sample(1:length(mu), size = m)
    mus = mu[index]
    p0s = p0[index]
    ind = !apply(mod, 2, function(x) {
        all(x == 1)
    })
    mod = cbind(mod[, ind])
    beta = cbind(beta[, ind])
    
    mumat = log2(mus + 0.001) + beta %*% t(mod)
    muvec = as.vector(mumat)
    sizevec = predict(fit, muvec)$y
    sizemat = matrix(sizevec, nrow = m)
    counts = sizemat * NA
    for (i in 1:m) {
        counts[i, ] = rbinom(n, prob = (1 - p0s[i]), size = 1) * 
            rnbinom(n, mu = 2^(mumat[i, ])*scaleFac, size = 2^(sizemat[i, ]))
    }
    list(counts = counts, mumat = mumat, p0 = p0s)
}

# Function to calculate Bias, Var, MSE
calculateMSERandom <- function(simDiffsObject, nGroups = 2)
{
    nMethods <- dim(simDiffsObject)[2] - 1
    N <- dim(simDiffsObject)[3] 
    
    trueDiffObject <- simDiffsObject[,1,1]
    
    simMean = sapply(1:nMethods, function(x){ rowMeans(simDiffsObject[,(x+1),]) })
    simBias = sapply(1:nMethods, function(x){ rowMeans(simDiffsObject[,(x+1),]) - trueDiffObject })
    simMSE = sapply(1:nMethods, function(x){ rowMeans( (sweep(simDiffsObject[,(x+1),], 1, trueDiffObject, FUN = "-") )^2 ) })
    simVar <- simMSE - (simBias)^2

    list( colMeans(simBias), colMeans((simBias)^2), colMeans(simVar), colMeans(simMSE))
}
```

## Monte Carlo Simulation Study 

Goal: estimate bias, var of difference in means from a zero-inflated
negative binomial. 

```{r}
# Generate an simulated data set of dim 1000x10 with two groups
group = rep(c(-1, 1),each=10) # biological groups
mod = model.matrix(~ -1 + group) # design matrix
nGenes <- 1e3 # number of genes
N <- 1000 # number of simulations
nMethods <- 3 # compare raw, QN, qsmooth
truthVal <- 1 # true LFC for DE genes
pDiffMax <- c(0.01, 0.05, 0.10, 0.25, 0.50) # proportion of DE genes

dat = vector("list", length(pDiffMax))
for(ind in 1:length(pDiffMax)){
    set.seed(21)
    pDiff <- runif(N, 0, pDiffMax[ind])
    simResults <- foreach(i = 1:N) %dopar% 
        {
    coeffs = cbind(c(rep(truthVal, floor(pDiff[i]*nGenes)), 
                     rep(0, nGenes - floor(pDiff[i]*nGenes))))

    sFs <- runif(20, 1, sFsMax) 
    simData <- create_read_numbers(mu = params$mu, fit = params$fit, 
                    p0 = params$p0, beta=coeffs, mod=mod, scaleFac = sFs)
    dat0 <- simData$counts
    
    # true difference in means of a zero-inflated NB 
    trueDiff <- rowttests(simData$mumat, factor(group))$dm * (1-simData$p0) 
    
    simDiffs = array(0, dim = c(dim(coeffs)[1], 3))
    
    fit <- rowttests(log2(dat0+1), factor(group))
    simDiffs[,1] <- fit$dm
    
    dat0.qn <- normalize.quantiles(dat0)
    fit <- rowttests(log2(dat0.qn+1), factor(group))
    simDiffs[,2] <- fit$dm
    
    dat0.qs <- qsmoothData(qsmooth(dat0, groupFactor = factor(group)))
    fit <- rowttests(log2(dat0.qs+1), factor(group))
    simDiffs[,3] <- fit$dm

    return(cbind(trueDiff, simDiffs))
    }
    simDiffs <- abind(simResults, along = 3)
    sumstats <- abs(abind(calculateMSERandom(simDiffs, nGroups = nG), along = 2))
    colnames(sumstats) <- c("Bias", "Bias2", "Var", "MSE")

    dat[[ind]] = data.frame(gather(as.data.frame(sumstats)),
                 "method" = factor(rep(c("raw", "qn", "qsmooth"), 4), c("raw", "qn", "qsmooth")))
}

datAll <- cbind(do.call("rbind", dat), "pDiff" = rep(pDiffMax, each = 12))

pBias <- datAll %>% filter(key %in% c("Bias")) %>% 
    ggplot(aes(x = method, y = value, fill = method)) + geom_bar(stat = "identity") + 
    facet_wrap(~pDiff, nrow=1) + ylab("Bias") + xlab(" ") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
pMSE <- datAll %>% filter(key %in% c("MSE")) %>% 
    ggplot(aes(x = method, y = value, fill = method)) + geom_bar(stat = "identity") + 
    facet_wrap(~pDiff, nrow=1) + ylab("MSE") + xlab(" ") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
pVar <- datAll %>% filter(key %in% c("Var")) %>% 
    ggplot(aes(x = method, y = value, fill = method)) + geom_bar(stat = "identity") + 
    facet_wrap(~pDiff, nrow=1) + ylab("Var") + xlab(" ") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
p <- plot_grid(pBias, pVar, pMSE, ncol=1, labels = LETTERS[1:3])

pdf(paste0(paper_path, "SimStudy/Figures/Bias_Var.pdf"), width = 10, height = 10)
print(p)
dev.off()
```



